language: R
cache: packages

apt_packages:
  - libgit2-dev

env:
  global:
    - ALLOWED_NOTES=0

r_packages:
  - lintr

r_github_packages:
  - jumpingrivers/inteRgrate

before_install:
  - sudo apt-get install -y ghostscript

script:
  - Rscript -e "inteRgrate::check_via_env(default = TRUE)"

r:
#  - oldrel
  - release
#  - devel
